# Директория для данных проекта
confluence_project_dir: /docker/confluence

# Параметры базы данных
confluence_postgres_dbname: confluence
confluence_postgres_user: confluence_bdadmin
confluence_postgres_password: "{{ lookup('ansible.builtin.pipe', 'openssl rand -hex 30') }}"

# Параметры Confluence
confluence_confluence_admin_email: admin@mail.ru
confluence_confluence_admin_login: admin
confluence_confluence_admin_password: admin
confluence_confluence_admin_fullname: Администратор